### PR TITLE
Fixtest

### PR DESCRIPTION
**Pull request by MrBartWolf**
Fixed the failing test and moved it out of the failing directory. This request should be merged after the one that changes dotests.sh

### CODE REVIEW

**Comment by lam2mo** [comment]
This should definitely be squashed or cleaned up before merging--there's a lot of clutter in the git history.

**Comment by MrBartWolf** [comment]
I'm trying to figure out how to clean up the commit history, that's new for me.

**Comment by lam2mo** [comment]
No worries. We'll probably just squash the commits when we merge the pull request. However, this branch is now in conflict so we may also decide it's easier to just cancel this pull request and make the change fresh once we clear up all the other testing-related pull requests.

**Comment by lam2mo** [comment]
**DO NOT MERGE.**

These changes will be added to #79 and then this pull request will be closed.

**Comment by lam2mo** [comment]
This PR is obsolete and replaced by changes in #79.

**Pull request closed without merging**
