### PR TITLE
Script to run sample files and compare against known outputs

### PR DESCRIPTION
**Pull request by hinescd**
I wrote a script (dotests.sh - open to renaming) that compiles, runs, and tests .lj files and then diffs their outputs against previously known outputs. This script can be helpful when making changes to the compiler so you can be sure that you didn't break anything that was previously working.

### CODE REVIEW

**Comment by hinescd** [comment]
I changed the compile script to run in quiet mode; that should suppress gradle's messages, but it still prints compiler messages if there are any

**Comment by Zamua** [comment]
Nice! last thing, can you squash those commits into one? You can keep the 'make a script to run all sample programs and test their outputs' message, throwaway others

**Comment by hinescd** [comment]
Squashed

**Comment by lam2mo** [comment]
Right now some of the tests are only valid for running xor testing. We should probably improve the tests at some point so that they are all valid for both running and testing. This would reduce confusion for newcomers as well.

**Pull request merged**
