### PR TITLE
Changed lj to work with running and testing only options.

### PR DESCRIPTION
**Pull request by MrBartWolf**
This is the null pull request for options. It should be clean from the current master, without the ui stuff.

### CODE REVIEW

**Comment by MrBartWolf** [comment]
I'm not sure why the testing check is not being performed. @Zamua @lam2mo

**Comment by lam2mo** [comment]
Hmmm. It seems it has failed: https://travis-ci.org/github/JMU-CS/less-java/builds/671871294

I'm not sure why it's not displaying that result here. Seems like it might be a file permissions problem again with `lj` not being executable.

**Comment by lam2mo** [comment]
Now it seems there's an output ordering issue: https://travis-ci.org/github/JMU-CS/less-java/builds/672301808

Did you inadvertently change the ordering of the testing vs. running output?

**Comment by MrBartWolf** [comment]
It wasn't inadvertent, you asked me to so that testing would come before running. I just forgot to change the order of the expected outputs of the tests. My bad.

**Comment by lam2mo** [comment]
Ah, gotcha. Seems there's still at least one that's in the wrong order: https://travis-ci.org/github/JMU-CS/less-java/builds/672306758

**Comment by MrBartWolf** [comment]
The branch was out of date. I'm still not sure why it isn't displaying but it passes travis now.

**Comment by lam2mo** [comment]
Can confirm: https://travis-ci.org/github/JMU-CS/less-java/builds/672317540

@Zamua?

**Comment by Zamua** [comment]
Looks fine to me. @lam2mo feel free to merge

**Comment by Zamua** [comment]
And could we link the issue that this is resolving?

**Comment by lam2mo** [comment]
Closes #92. Thanks @MrBartWolf!

**Comment by lam2mo** [comment]
Sorry, I thought that the "closes" message would clean it up. Clearly not.

**Pull request merged**
