### PR TITLE
exit on antlr parse errors

### PR DESCRIPTION
**Pull request by Zamua**
This is how to solve #76. I believe this breaks our tests and will break our build. I don't know if I have time to fix the tests at the moment. Perhaps @MrBartWolf can take it from here?

### CODE REVIEW

**Comment by lam2mo** [comment]
Looks like it passes the Travis build.

**Comment by Zamua** [comment]
Ah okay, so the tests that actually contribute to the build decision don't have syntax errors then. great. I'll make this not a draft

**Comment by hinescd** [comment]
Looks good to me

**Comment by lam2mo** [comment]
Does this fix #76?

**Pull request merged**
