### PR TITLE
Update Gradle to 5.4.1

### PR DESCRIPTION
**Pull request by kylelaker**
This will allow for building against newer versions of Java such as
Java 10 (used in the CS labs) and 11 (which is likely to be generally
available soon). And much more.

### CODE REVIEW

**Comment by kylelaker** [comment]
I've made this depend on #39 to ensure that the changes actually are tested by Travis.

**Comment by lam2mo** [comment]
I'm going to let @Zamua handle this because I'm unsure what the ramifications of upgrading Gradle are throughout the rest of the project.

**Comment by Zamua** [comment]
I also don't know the full ramifications, but if travis passed, then I don't see any issues.

**Comment by lam2mo** [comment]
Point of interest: I've not yet seen the Travis build fail, so I'm not sure we should be using that as our gold standard just quite yet... :P

**Comment by ripleymj** [comment]
Also, I've met the author of the Travis tests....

**Pull request merged**
