### PR TITLE
Clear static analysis errors between test runs

### PR DESCRIPTION
**Pull request by hinescd**
From what I saw with @lam2mo after the meeting today, this should fix the build issues. I can't verify this though, since the tests were already passing on my machine anyway.

### CODE REVIEW

**Comment by lam2mo** [comment]
We can potentially see whether it fixes the issue in the [Travis logs](https://travis-ci.org/JMU-CS/less-java), right? If I'm reading those correctly, it's now passing 2/3 versions of Java and the remaining issue seems to be something about a 403 when pulling an ANLTR build file. The file exists when I put the URL in my browser, so that seems really odd to me.

**Comment by hinescd** [comment]
It [looks like](https://travis-ci.community/t/continuous-maven-repo-403/3908/9) this is an issue between Travis and Maven servers. Is there a way to retry the build?

**Comment by lam2mo** [comment]
Yeah turns out I can through the Travis website. Looks good!

**Comment by lam2mo** [comment]
For the record, I also had to restart two jobs due to the same issue for the pull request merge commit before I finally got all three to pass. I'm hoping this is not something that will continue. If so, we should definitely look into an alternative integration test solution (maybe part of #50?).

Our "build passing" icon is back! 😄

**Pull request merged**
